version: "3.3"

services:
  backup:
    image: mazzolino/restic
    hostname: docker
    environment:
      BACKUP_CRON: "0 30 3 * * *"
      RESTIC_REPOSITORY: b2:my-repo:/restic
      RESTIC_PASSWORD: supersecret
      RESTIC_BACKUP_SOURCES: /mnt/volumes
      #RESTIC_BACKUP_ARGS: -v
      RESTIC_BACKUP_TAGS: docker-volumes
      RESTIC_FORGET_ARGS: --prune --keep-last 14 --keep-daily 1
      B2_ACCOUNT_ID: xxxxxxx
      B2_ACCOUNT_KEY: yyyyyyyy
      TZ: Europe/Berlin
    volumes:
      - /var/lib/docker/volumes:/mnt/volumes:ro

  prune:
    image: mazzolino/restic
    hostname: docker
    environment:
      PRUNE_CRON: "0 0 4 * * *"
      RESTIC_REPOSITORY: b2:my-repo:/restic
      RESTIC_PASSWORD: supersecret
      B2_ACCOUNT_ID: xxxxxxx
      B2_ACCOUNT_KEY: yyyyyyyy
      TZ: Europe/Berlin
