version: "3.3"

services:
  backup:
    image: mazzolino/restic
    hostname: docker
    environment:
      RUN_ON_STARTUP: "true"
      BACKUP_CRON: "0 30 3 * *"
      RESTIC_REPOSITORY: b2:my-repo:/restic
      RESTIC_PASSWORD: supersecret
      RESTIC_BACKUP_SOURCES: /mnt/volumes
      RESTIC_BACKUP_ARGS: >-
        --tag docker-volumes
        --exclude='some-folder/cache'
        --exclude='*.tmp'
        --verbose
      RESTIC_FORGET_ARGS: >-
        --keep-last 10
        --keep-daily 7
        --keep-weekly 5
        --keep-monthly 12
      B2_ACCOUNT_ID: xxxxxxx
      B2_ACCOUNT_KEY: yyyyyyyy
      TZ: Europe/Berlin
    volumes:
      - /var/lib/docker/volumes:/mnt/volumes:ro

  prune:
    image: mazzolino/restic
    hostname: docker
    environment:
      RUN_ON_STARTUP: "true"
      PRUNE_CRON: "0 0 4 * *"
      RESTIC_REPOSITORY: b2:my-repo:/restic
      RESTIC_PASSWORD: supersecret
      B2_ACCOUNT_ID: xxxxxxx
      B2_ACCOUNT_KEY: yyyyyyyy
      TZ: Europe/Berlin
